### ISSUE TITLE
ear project dependencies task StackOverflowError

### ISSUE THREAD

**Issue by jjteo74** [nebula-plugins/gradle-resolution-rules-plugin#41]
Only `dependencies` task face this error. Other tasks such as `assemble`, `clean`, `build`, etc. run successfully. The same task using version `1.6.5` works fine though.

Gradle: 2.14
Java: 1.8.0_91
OS: MacOS 10.11.5
Machine: MacBook Pro 15' 2014

Run `gradle dependencies -s`  with the following `build.gradle`

``` groovy
plugins {
    id "nebula.resolution-rules" version "1.7.1"
}

apply plugin:'ear'

dependencies {
    resolutionRules "com.netflix.nebula:gradle-resolution-rules:0.26.0"
}
```

Output: -

```
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

archives - Configuration for archive artifacts.
:dependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Failed to notify dependency resolution listener.
   > java.lang.StackOverflowError (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
  (TRUNCATED...)
        ... 68 more
Caused by: java.lang.StackOverflowError
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:620)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.run(DefaultConfiguration.java:150)
        at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:267)
        at org.gradle.api.internal.DefaultDomainObjectCollection.remove(DefaultDomainObjectCollection.java:208)
        at org.gradle.api.internal.DelegatingDomainObjectSet.remove(DelegatingDomainObjectSet.java:109)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.replaceCurrent(DefaultArtifactPublicationSet.java:53)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.addCandidate(DefaultArtifactPublicationSet.java:42)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:162)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:160)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:81)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.replaceCurrent(DefaultArtifactPublicationSet.java:54)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.addCandidate(DefaultArtifactPublicationSet.java:42)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:162)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:160)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:81)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.replaceCurrent(DefaultArtifactPublicationSet.java:54)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.addCandidate(DefaultArtifactPublicationSet.java:42)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:162)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:160)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:81)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.replaceCurrent(DefaultArtifactPublicationSet.java:54)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.addCandidate(DefaultArtifactPublicationSet.java:42)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:162)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:160)
    (REPEAT...)
```

**Comment by DanielThomas** [comment]
I can't see anything like that here. Let us know if you're still seeing anything like this, and we'll take a look.
